name: Build, Run and Publish binary

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Create and use builder
        run: |
          docker buildx create --name captions-builder --use
          docker buildx inspect --bootstrap

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/captions-${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.platform }}

      - name: Run the Docker image
        run: mkdir -p ./${{ matrix.platform }} && docker run --platform=${{ matrix.platform }} -v ./${{ matrix.platform }}:/app/out ghcr.io/${{ github.repository }}/captions-${{ matrix.platform }}

      - name: Calculate binary checksum
        id: checksum
        run: echo "::set-output name=sha256::$(sha256sum ./${{ matrix.platform }}/captions | awk '{print $1}')"

      - name: Save platform as a new variable
        id: save_platform
        run: echo "::set-output name=platform::$(echo ${{ matrix.platform }} | tr '/' '-')"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.save_platform.outputs.platform }}
          path: ./${{ matrix.platform }}/captions

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download amd64 artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-amd64
          path: ./linux/amd64/captions
      - name: Download arm64 artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-arm64
          path: ./linux/arm64/captions
      - name: Get commit SHA
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_sha.outputs.sha }}
          release_name: ${{ steps.get_sha.outputs.sha }}
          body: |
            Commit SHA: ${{ steps.get_sha.outputs.sha }}
            Binary SHA256 checksum (linux/amd64): ${{ needs.build.outputs.checksum.sha256['linux/amd64'] }}
            Binary SHA256 checksum (linux/arm64): ${{ needs.build.outputs.checksum.sha256['linux/arm64'] }}
          draft: false
          prerelease: false
      - name: Upload Release Asset for linux/amd64
        id: upload-release-asset-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux/amd64/captions
          asset_name: captions-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset for linux/arm64
        id: upload-release-asset-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux/arm64/captions
          asset_name: captions-linux-arm64
          asset_content_type: application/octet-stream
